name: nixvim

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # runs daily at midnight

jobs:
  lockfile:
    name: Update flake.lock
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Nix
        uses: cachix/install-nix-action@v22
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@v18
        with:
          pr-labels: |
            dependencies
          token: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
      - name: Auto-merge update
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
      - name: Install Nix
        uses: cachix/install-nix-action@v22
        with:
          extra_nix_config: |
            max-jobs = 4
      - name: Install Cachix
        uses: cachix/cachix-action@v12
        with:
          name: nickhu
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Build nixvim
        run: |
          nix build -L github:NickHu/nixvim-flake/update_flake_lock_action
  test:
      - name: Install Nix
        uses: cachix/install-nix-action@v22
      - name: Install Cachix
        uses: cachix/cachix-action@v12
        with:
          name: nickhu
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Check nixvim
        run: |
          nix flake check -L github:NickHu/nixvim-flake/update_flake_lock_action
