name: nixvim

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Build and cache
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
      - name: Install Nix
        uses: cachix/install-nix-action@v25
        with:
          extra_nix_config: |
            max-jobs = 4
      - name: Install Cachix
        uses: cachix/cachix-action@v13
        with:
          name: nickhu
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Build nixvim
        run: |
          nix build -L github:NickHu/nixvim-flake?rev=${{ github.sha }}
  test:
    name: Check config
    runs-on: ubuntu-latest
    steps:
      - name: Install Nix
        uses: cachix/install-nix-action@v25
      - name: Install Cachix
        uses: cachix/cachix-action@v13
        with:
          name: nickhu
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Check nixvim
        run: |
          nix flake check -L github:NickHu/nixvim-flake?rev=${{ github.sha }}
